"""data_quality/gen_windows_md.py — render DATA_QUALITY_WINDOWS.md from
``data_quality.windows.WINDOWS``.

The Markdown file is a VIEW. Every byte of it is generated here, so it can
never disagree with the register it describes — the same arrangement as
``features/gen_schema_md.py`` -> ``features/SCHEMA.md`` §3, adopted for the
same reason (a hand-kept table drifted from the code once in production and
cost 901 of 903 tickers a liquidity gate for months).

Usage:
    python3 data_quality/gen_windows_md.py           # print the render
    python3 data_quality/gen_windows_md.py --write   # rewrite the file
    python3 data_quality/gen_windows_md.py --check   # exit 1 on drift
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from data_quality.windows import WINDOWS, QualityWindow

WINDOWS_MD = Path(__file__).resolve().parent.parent / "DATA_QUALITY_WINDOWS.md"

_PREAMBLE = """<!-- GENERATED by data_quality/gen_windows_md.py from
data_quality/windows.py — DO NOT EDIT. Edit the register and re-run
`python3 data_quality/gen_windows_md.py --write`. CI fails on drift. -->

# Known data-quality windows

Date ranges over which a published artifact is known to carry a **measured**
defect that has been **ruled on** and deliberately left in place. This is not
a backlog: an issue is opened to be closed, while a window is a permanent
property of data already on S3 and is meant to be read by whoever reads
those dates.

A window is admitted only when the defect is measured with durable evidence,
the affected data is already published and staying published, and a
disposition has been ruled. A defect still being fixed forward belongs in the
backlog until the forward fix lands; what the fix cannot reach belongs here.

**Register:** `data_quality/windows.py` is authoritative — this file is
rendered from it. Consumers should call
`data_quality.overlapping(artifact, start, end)` rather than reading this
page, so that a run over affected dates refuses or attaches the caveat
without depending on a human having read it.

"""


def _fmt_date(value) -> str:
    return value.isoformat() if value is not None else "open"


def render_window(window: QualityWindow) -> str:
    """Render one window as a heading, a fact table, and its notes."""
    lines: list[str] = []
    lines.append(f"## `{window.window_id}`")
    lines.append("")
    lines.append(window.defect)
    lines.append("")
    lines.append("| | |")
    lines.append("|---|---|")
    lines.append(
        f"| **Affected dates** | {_fmt_date(window.first_affected)} "
        f"through {_fmt_date(window.last_affected)} |"
    )
    artifacts = "<br>".join(f"`{a}`" for a in window.artifacts)
    lines.append(f"| **Artifacts** | {artifacts} |")
    for label, value in window.measured.items():
        lines.append(f"| **{label}** | {value} |")
    lines.append(f"| **Evidence** | {window.evidence} |")
    lines.append(
        f"| **Disposition** | `{window.disposition}` — ruled by "
        f"{window.ruled_by} on {_fmt_date(window.ruled_on)} |"
    )
    lines.append(f"| **Re-exam trigger** | {window.reexam_trigger} |")
    lines.append("")
    for note in window.notes:
        lines.append(f"- {note}")
    if window.notes:
        lines.append("")
    return "\n".join(lines)


def render() -> str:
    """Render the whole file."""
    body = "\n".join(render_window(w) for w in WINDOWS)
    if not WINDOWS:
        body = "_No windows are currently declared._\n"
    return _PREAMBLE + body


def main(argv: list[str]) -> int:
    fresh = render()
    if "--write" in argv:
        WINDOWS_MD.write_text(fresh, encoding="utf-8")
        print(f"Wrote {WINDOWS_MD}.")
        return 0
    if "--check" in argv:
        if not WINDOWS_MD.exists():
            print(
                f"MISSING: {WINDOWS_MD} does not exist. Run "
                "`python3 data_quality/gen_windows_md.py --write`.",
                file=sys.stderr,
            )
            return 1
        if WINDOWS_MD.read_text(encoding="utf-8") != fresh:
            print(
                "DRIFT: DATA_QUALITY_WINDOWS.md does not match a fresh render "
                "from data_quality/windows.py. Run "
                "`python3 data_quality/gen_windows_md.py --write` and commit "
                "the result.",
                file=sys.stderr,
            )
            return 1
        print("DATA_QUALITY_WINDOWS.md matches the register. OK.")
        return 0
    print(fresh)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
