"""data_quality/windows.py — the declared register of KNOWN DATA-QUALITY
WINDOWS: date ranges over which a published artifact is known to carry a
defect that was measured, ruled on, and deliberately left in place.

**Why this exists as code and not as a tracked issue.** A GitHub issue is a
unit of *work* — it is opened to be closed, it is counted in backlog health,
and once closed it stops being read. A known-defect window is the opposite:
it is a permanent *property of data already on S3*, it outlives every fix,
and its whole value is that a consumer reading those dates can find it. The
unsettled-bar window below was first recorded as
``alpha-engine-config-I11367`` and moved here for exactly that reason
(Brian, 2026-09-22): the artifact tracking this class must be permanent and
easy to reach, not a row in a queue.

**Source of truth.** This module is authoritative. ``DATA_QUALITY_WINDOWS.md``
at the repo root is a RENDERED view of it, regenerated by
``data_quality/gen_windows_md.py --write`` and drift-checked in CI by
``tests/test_data_quality_windows_contract.py``. This mirrors the
``features/registry.py::CATALOG`` -> ``features/SCHEMA.md`` §3 arrangement,
which exists because a hand-maintained table drifted from the code once in
production (the ``avg_volume_20d`` units incident, SCHEMA.md §1) — the same
reason applies here and the same shape answers it.

**What belongs here.** A window is admitted when ALL of the following hold:

1. The defect is **measured**, not suspected, and the measurement has a
   durable artifact behind it (``evidence``).
2. The affected data is **already published** and will stay published —
   a defect caught before anything landed is a bug, not a window.
3. A **disposition has been ruled**: either the data is being left as-is, or
   a remediation is scheduled. "We should probably look at this" is not a
   disposition and does not belong here.

A defect still being fixed forward is NOT a window until the forward fix has
landed and the historical residue is what remains. Use the backlog for the
fix; use this register for what the fix cannot reach.

**Consuming this register.** ``overlapping(artifact, start, end)`` answers
"does any declared window touch the dates I am about to read". A consumer
that grades a result over historical data is expected to call it and either
refuse or attach the caveat to its output, rather than relying on a human
having read the Markdown.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date

__all__ = ["QualityWindow", "WINDOWS", "overlapping", "window_by_id"]


#: A window's disposition — what was RULED about the affected data, not what
#: is planned for the code. ``no_remediation`` means the data stays as it is.
#: ``remediation_pending`` means a rewrite is scheduled and named in
#: ``reexam_trigger``. ``remediated`` means the affected range has been
#: rewritten and the window is kept for the historical record only.
DISPOSITIONS = ("no_remediation", "remediation_pending", "remediated")


@dataclass(frozen=True)
class QualityWindow:
    """One declared known-defect window over published data.

    ``last_affected`` is ``None`` for a window whose closing date is not yet
    established — never a far-future sentinel, which reads as a real date to
    every consumer that does not know the convention.
    """

    window_id: str
    #: S3 key templates this window applies to, written exactly as the
    #: producing code writes them (``{date}`` / ``{trading_day}`` intact).
    artifacts: tuple[str, ...]
    first_affected: date
    last_affected: date | None
    #: One line. What is wrong with the data, in the reader's terms.
    defect: str
    #: Measured magnitudes, ``{label: value}``. Every entry is a number that
    #: was observed, never an estimate or a tolerance.
    measured: dict[str, str]
    #: Where the measurement can be re-read. An S3 key, a report, an artifact.
    evidence: str
    disposition: str
    ruled_by: str
    ruled_on: date
    #: The CONDITION that re-opens the disposition. Never a date — a window
    #: whose re-exam is a calendar entry gets re-read to produce the same
    #: answer until someone stops reading it.
    reexam_trigger: str
    #: Free-form detail: affected readers, what the forward fix was, what a
    #: remediation would have to do. Rendered as prose under the table.
    notes: tuple[str, ...] = field(default_factory=tuple)

    def covers(self, day: date) -> bool:
        """True when ``day`` falls inside this window."""
        if day < self.first_affected:
            return False
        return self.last_affected is None or day <= self.last_affected


WINDOWS: tuple[QualityWindow, ...] = (
    QualityWindow(
        window_id="unsettled-session-bar-2026",
        artifacts=(
            "features/{date}/technical.parquet",
            "features/{date}/interaction.parquet",
            "features/{date}/alternative.parquet",
            "features/{date}/macro.parquet",
            "features/{date}/fundamental.parquet",
            "staging/daily_closes/{date}.parquet",
            "market_data/eod_closes/{date}.json",
        ),
        # The v1 postclose pipeline has fetched the session bar at ~16:06 ET
        # for as long as it has been chained off the executor daemon's
        # shutdown. The opening date is the first trading day for which the
        # affected dated artifacts still exist on S3, not the first day the
        # behaviour began — the behaviour predates the retention.
        first_affected=date(2026, 5, 1),
        last_affected=date(2026, 9, 22),
        defect=(
            "The trading day's bar was fetched ~16:06 ET, about 1.5 hours "
            "before the consolidated tape settles, so Close and Volume are "
            "the vendor's unsettled intraday snapshot rather than the "
            "official session values."
        ),
        measured={
            "tickers compared": "920 of 920",
            "Close drift (median)": "2.7 bps",
            "Close drift (max)": "16.4 bps",
            "Volume shortfall (median)": "20.5 %",
            "Volume shortfall (worst names)": "~40 %",
        },
        evidence=(
            "s3://alpha-engine-research/data_collection/parity/2026-09-21.json"
            " — the same-day shadow parity report that first graded the "
            "unsettled bar against the settled one"
        ),
        disposition="no_remediation",
        ruled_by="Brian",
        ruled_on=date(2026, 9, 22),
        reexam_trigger=(
            "The first time a GRADED result depends on these dates: a "
            "champion/challenger arm registered from a scoring run whose "
            "window includes them, a predictor training window drawn from "
            "features/{date} rather than from ArcticDB, or a v2 phase-4/5 "
            "backtest gating a promotion."
        ),
        notes=(
            "Forward fix landed 2026-09-22 (nousergon-data PR1863, PR1867, "
            "PR1868): the standalone EOD collection fires at 18:15 ET, and "
            "dates.assert_settled_bar refuses a D03/D19 write whose "
            "trading-day row was fetched before settlement. This window is "
            "the historical residue that fix cannot reach.",
            "ArcticDB — and therefore crucible-predictor — is NOT affected "
            "beyond a single overnight. weekly_collector._should_skip_"
            "morning_enrich skips only when target_date < arctic_last_date, "
            "so the D+1 07:30 ET Polygon T+1 overwrite always runs and "
            "restores the settled row. Exposure is bounded at roughly "
            "16:06 ET on D to 07:30 ET on D+1.",
            "Known readers of the dated feature-store artifacts, measured "
            "2026-09-22: crucible-research scoring/factor_scoring.py, "
            "scoring/universe_board.py, data/fetchers/feature_store_reader.py, "
            "data/scanner_orchestrator.py; crucible-dashboard "
            "views/13_Feature_Store.py (display only).",
            "A remediation, if it is ever ruled, must rewrite the affected "
            "dated prefixes from the settled price cache AND write a "
            "backfilled_at marker beside each rewritten prefix — a "
            "re-derived artifact that is indistinguishable from an original "
            "one destroys the reproducibility of every run that read the "
            "original.",
        ),
    ),
)


def window_by_id(window_id: str) -> QualityWindow:
    """Return the window with ``window_id``, or raise ``KeyError``.

    Raises rather than returning ``None``: a caller naming a window that does
    not exist has a typo or a stale reference, and silently returning "no
    known defect" is the failure this register exists to prevent.
    """
    for window in WINDOWS:
        if window.window_id == window_id:
            return window
    raise KeyError(
        f"no declared quality window {window_id!r} — "
        f"known: {sorted(w.window_id for w in WINDOWS)}"
    )


def overlapping(
    artifact: str, start: date, end: date
) -> tuple[QualityWindow, ...]:
    """Windows touching ``artifact`` anywhere in ``[start, end]``.

    ``artifact`` is matched against the declared key TEMPLATES literally, so
    callers pass the template (``features/{date}/technical.parquet``), not a
    resolved key. Matching resolved keys would need a parser per template
    shape and would silently miss the ones it could not parse.
    """
    if end < start:
        raise ValueError(f"end {end} precedes start {start}")
    hits = []
    for window in WINDOWS:
        if artifact not in window.artifacts:
            continue
        if window.first_affected > end:
            continue
        if window.last_affected is not None and window.last_affected < start:
            continue
        hits.append(window)
    return tuple(hits)
