"""Load and validate the unit descriptors under ``registry.d/units/``.

`data_collection_plan_260914.md` §4.1: the descriptors are the ONLY source of
units. Nothing downstream hand-lists one — a hand-maintained monitored-things
list drifts, and its drift is invisible because the missing rows produce no
signal (`observability-policy` §2.2).

So this module's job is not "parse YAML", it is **refuse a descriptor set that
would silently grade less than it claims**: a missing column, an unknown state,
a guard marked N/A with no code from the closed taxonomy, a duplicate unit id.
Every refusal here is loud at import, because the alternative is a board that
renders complete over a unit nobody declared.
"""

from __future__ import annotations

import pathlib
import re
from dataclasses import dataclass
from typing import Any

import yaml

__all__ = [
    "AUDIT_CELL_STATES",
    "AUDIT_COLUMNS",
    "EXTERNALLY_OWNED_OBSERVABILITY_ROWS",
    "GUARD_CLASSES",
    "NA_TAXONOMY",
    "UNITS_DIR",
    "Unit",
    "load_units",
]

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
UNITS_DIR = REPO_ROOT / "registry.d" / "units"

#: The nine scored columns of the audit's §3 unit register, in its own order.
#: One base clause is generated per unit per column, and
#: `tests/test_every_audit_cell_is_a_clause.py` grades that mapping as a
#: bijection. Changing this tuple changes the clause count, which is why it is
#: declared once and read everywhere.
AUDIT_COLUMNS: tuple[str, ...] = (
    "identity",
    "consumers",
    "schema_contract",
    "artifact_registry",
    "observability_row",
    "run_record",
    "detector",
    "console_entity",
    "survives_phase4",
)

#: The audit's own cell vocabulary (§2, "Cell vocabulary"). Closed: a tenth
#: value would be a reading nobody defined, and a descriptor carrying one is
#: refused rather than rendered.
AUDIT_CELL_STATES: frozenset[str] = frozenset({"PRESENT", "ABSENT", "BROKEN", "UNVERIFIED"})

#: The six silent-degradation classes of audit §4.1, plus the cross-check the
#: plan adds on the two units that write the same key (§2 row 5).
GUARD_CLASSES: tuple[str, ...] = (
    "empty_fresh",
    "cardinality",
    "units",
    "pit",
    "vendor_fallback",
    "success_without_output",
)
OPTIONAL_GUARD_CLASSES: tuple[str, ...] = ("vendor_crosscheck",)

#: Units whose observability row is hand-authored OUTSIDE this repo (in
#: `nous-ergon-ops/governance/observability.d/`) rather than generated by
#: `scripts/gen_observability_rows.py` — single source of truth for BOTH the
#: generator (which must not also emit a duplicate row here) and
#: `data_gate/unit_readers.py::read_observability_row` (which must not grade
#: the unit UNMET just because this repo carries no row of its own;
#: alpha-engine-config-I10870 — the two were declaring opposite things about
#: D39 before this constant unified them: the generator's docstring said "flip
#: the EXISTING ops-side row", the reader only ever looked in this repo).
EXTERNALLY_OWNED_OBSERVABILITY_ROWS: dict[str, str] = {
    "D39": "nousergon-data-inst-ownership-weekly",
}

#: `observability-policy` §3.5's CLOSED N/A taxonomy. A guard class, a freshness
#: deadline or a completeness floor may be marked not-applicable ONLY with one
#: of these codes beside it. The plan (§4.1) states the rule and the consequence
#: in one line: *an N/A with no reason is UNMET*. A free-text excuse is how a
#: class quietly stops being graded.
NA_TAXONOMY: frozenset[str] = frozenset(
    {
        "N/A-NOT-IMPL",  # the thing is not built
        "N/A-NOT-RUN",  # it did not run this cycle (disabled, manual, on-demand)
        "N/A-LOW-N",  # it ran, and the sample is below its floor
        "N/A-MISSING-INPUT",  # it ran, and a required input was absent
    }
)

#: The shape `run_manifest_retention` must take: a positive integer count of
#: days (`alpha-engine-config-I10831` deliverable 3; precedent: D37's
#: `run_manifest_retention: 400 days`). A free-text value is exactly the kind
#: of undeclared knob the field exists to end.
_RETENTION_PATTERN = re.compile(r"^\d+\s+days$")

#: A unit firing more than once an hour takes one manifest per tick, not one
#: per day — its `run_manifest_prefix` is high-cardinality and its S3 cost is
#: a decision, not a default. `trigger.cadence_minutes` mirrors the field name
#: `nous-ergon-ops` registry rows already use for the same fact.
_SUB_HOURLY_MINUTES = 60

_REQUIRED_TOP_LEVEL = (
    "unit_id",
    "component_id",
    "owning_repo",
    "title",
    "lifecycle",
    "trigger",
    "writes",
    "consumers",
    "contract",
    "registry_rows",
    "run_manifest_prefix",
    "detectors",
    "freshness",
    "completeness",
    "guards",
    "audit",
    "clause_phase",
)


CONSUMER_REPOS_PATH = REPO_ROOT / "data_gate" / "config" / "consumer_repos.yaml"

#: A unit's connection to a surviving consumer (`alpha-engine-config-I10873`).
#: Closed: the board publishes exactly these values on every unit row.
CONNECTION_STATES: tuple[str, ...] = ("connected", "unconnected", "retired")

#: The one `consumers_decision.decision` value the gate accepts today: Brian's
#: 2026-09-15 ruling — keep collecting, render "exists, no consumer", allow
#: reincorporation. A retirement is `lifecycle: retired`, not a decision here.
CONSUMERS_DECISIONS: frozenset[str] = frozenset({"kept-unconnected"})
_CONSUMERS_DECISION_FIELDS = ("decision", "ruled_by", "ruled_on", "ruling", "reason", "reexam")
_ISO_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def consumer_repo(entry: str) -> str:
    """The repository part of a ``repo:path`` consumer entry."""
    return str(entry).strip().split(":", 1)[0]


_CONSUMER_REPO_CLASSES: dict[str, frozenset[str]] | None = None


def consumer_repo_classes() -> dict[str, frozenset[str]]:
    """``{"surviving": …, "retiring": …}`` from `consumer_repos.yaml`, cached."""
    global _CONSUMER_REPO_CLASSES
    if _CONSUMER_REPO_CLASSES is None:
        document = yaml.safe_load(CONSUMER_REPOS_PATH.read_text(encoding="utf-8"))
        surviving = frozenset(document["surviving"])
        retiring = frozenset(document["retiring"])
        if not surviving or surviving & retiring:
            raise DescriptorError(
                f"{CONSUMER_REPOS_PATH.name}: `surviving` must be non-empty and disjoint from "
                f"`retiring` (overlap: {sorted(surviving & retiring)})"
            )
        _CONSUMER_REPO_CLASSES = {"surviving": surviving, "retiring": retiring}
    return _CONSUMER_REPO_CLASSES


class DescriptorError(ValueError):
    """A descriptor that cannot be graded. Always fatal, never skipped.

    Skipping a malformed descriptor would drop its unit from the board's
    denominator, and a board whose denominator shrinks when a file breaks
    reports improving coverage as its coverage disappears.
    """


@dataclass(frozen=True)
class Unit:
    """One audit unit, as its committed descriptor declares it."""

    unit_id: str
    path: pathlib.Path
    raw: dict[str, Any]

    @property
    def component_id(self) -> str:
        return str(self.raw["component_id"])

    @property
    def title(self) -> str:
        return str(self.raw["title"])

    @property
    def lifecycle(self) -> str:
        return str(self.raw["lifecycle"])

    @property
    def retired(self) -> bool:
        """Declared retired — every clause renders RETIRED and grades nothing."""
        return self.lifecycle == "retired"

    @property
    def retirement_summary(self) -> str:
        block = self.raw.get("retirement") or {}
        return f"{str(block.get('ruling')).strip()} — {' '.join(str(block.get('reason')).split())}"

    @property
    def declared_consumers(self) -> list[str]:
        return [str(c).strip() for c in self.raw.get("consumers") or []]

    @property
    def surviving_consumers(self) -> list[str]:
        """Declared consumers in a repo that survives v2 phase 4 — the only
        ones that count as a connection (plan §3)."""
        surviving = consumer_repo_classes()["surviving"]
        return [c for c in self.declared_consumers if consumer_repo(c) in surviving]

    @property
    def retiring_consumers(self) -> list[str]:
        retiring = consumer_repo_classes()["retiring"]
        return [c for c in self.declared_consumers if consumer_repo(c) in retiring]

    @property
    def connection(self) -> str:
        """``connected`` / ``unconnected`` / ``retired`` — one of
        :data:`CONNECTION_STATES`, derived from the descriptor alone.

        `alpha-engine-config-I10873` (Brian ruling 2026-09-15). A consumer list
        that names only v1 repos is UNCONNECTED, exactly like an empty one.
        """
        if self.retired:
            return "retired"
        return "connected" if self.surviving_consumers else "unconnected"

    @property
    def consumers_decision(self) -> dict[str, str] | None:
        block = self.raw.get("consumers_decision")
        return {k: " ".join(str(v).split()) for k, v in block.items()} if isinstance(block, dict) else None

    @property
    def connection_reason(self) -> str:
        """Why the unit is (un)connected, as one line a reader can act on."""
        if self.connection == "retired":
            return f"retired: {self.retirement_summary}"
        if self.connection == "connected":
            return f"read by {len(self.surviving_consumers)} surviving consumer(s): {self.surviving_consumers}"
        parts = []
        if self.retiring_consumers:
            parts.append(f"declared readers are all v1 repos retiring in crucible v2 phase 4: {self.retiring_consumers}")
        else:
            parts.append("no consumer declared")
        decision = self.consumers_decision
        if decision:
            parts.append(
                f"{decision['decision']} by {decision['ruled_by']} on {decision['ruled_on']} "
                f"({decision['ruling']}): {decision['reason']}; re-exam: {decision['reexam']}"
            )
        else:
            reason = " ".join(str(self.raw.get("consumers_reason") or "").split())
            if reason:
                parts.append(f"reason: {reason}")
            parts.append("NO recorded keep/retire decision (plan §3 finding)")
        return "; ".join(parts)

    @property
    def component(self) -> int:
        return int(self.raw.get("component", 1))

    @property
    def graded_on(self) -> str | None:
        value = self.raw.get("graded_on")
        return None if value is None else str(value)

    @property
    def cells(self) -> dict[str, str]:
        return dict(self.raw["audit"]["cells"])

    @property
    def clause_phase(self) -> dict[str, int]:
        return {k: int(v) for k, v in self.raw["clause_phase"].items()}

    @property
    def writes(self) -> list[str]:
        return list(self.raw["writes"])

    @property
    def guards(self) -> dict[str, dict[str, Any]]:
        return dict(self.raw["guards"])

    @property
    def freshness_family(self) -> str | None:
        freshness = self.raw.get("freshness") or {}
        return freshness.get("family")

    @property
    def completeness(self) -> dict[str, Any] | None:
        """The unit's declared cardinality block: ``denominator``, ``floor``,
        ``status``, ``note`` (`data_collection_plan_260914.md` §2 row 2). ``None``
        when the raw block is empty/absent — most units publish no single
        countable denominator and declare no completeness block at all."""
        value = self.raw.get("completeness")
        return dict(value) if isinstance(value, dict) and value else None

    @property
    def run_manifest_prefix(self) -> str:
        return str(self.raw["run_manifest_prefix"])

    @property
    def cadence_minutes(self) -> int | None:
        trigger = self.raw.get("trigger") or {}
        value = trigger.get("cadence_minutes")
        return None if value is None else int(value)

    @property
    def run_manifest_retention_days(self) -> int | None:
        retention = self.raw.get("run_manifest_retention")
        if retention is None:
            return None
        return int(str(retention).strip().split()[0])


def _check_na(where: str, block: dict[str, Any], unit_id: str) -> None:
    """A not-applicable declaration carries a code from the closed taxonomy."""
    code = block.get("na_code")
    if code is None:
        raise DescriptorError(
            f"{unit_id}: {where} is marked not_applicable with no `na_code`. "
            "observability-policy §3.5's N/A taxonomy is CLOSED and the plan's rule is "
            "explicit: an N/A with no reason is UNMET. A free-text excuse is how a class "
            f"quietly stops being graded. Use one of {sorted(NA_TAXONOMY)}."
        )
    if code not in NA_TAXONOMY:
        raise DescriptorError(
            f"{unit_id}: {where} declares na_code {code!r}, which is not in "
            f"observability-policy §3.5's closed taxonomy {sorted(NA_TAXONOMY)}. A code "
            "outside the set is a new engineering state nobody has defined a rendering "
            "for."
        )


def _check_retention(unit_id: str, document: dict[str, Any], path: pathlib.Path) -> None:
    """A sub-hourly unit declares a validated `run_manifest_retention`.

    `alpha-engine-config-I10831` deliverable 3. D37 (metron-intraday, 5-minute
    cadence) is the precedent this generalizes: ~288 manifests/day against
    ~1/day for every other unit is a bucket-cost decision that belongs on the
    record, not left to the bucket's default. A cadence at or above 60 minutes
    is exempt — the field is optional there, but if declared anyway its shape
    is still checked, so a stray declaration can never silently mean nothing.
    """
    trigger = document.get("trigger") or {}
    raw_cadence = trigger.get("cadence_minutes")
    cadence_minutes: int | None = None
    if raw_cadence is not None:
        try:
            cadence_minutes = int(raw_cadence)
        except (TypeError, ValueError):
            raise DescriptorError(
                f"{path.name}: trigger.cadence_minutes must be an integer number of "
                f"minutes, got {raw_cadence!r}."
            )
        if cadence_minutes <= 0:
            raise DescriptorError(
                f"{path.name}: trigger.cadence_minutes must be positive, got {cadence_minutes}."
            )

    retention = document.get("run_manifest_retention")
    reason = document.get("run_manifest_retention_reason")
    sub_hourly = cadence_minutes is not None and cadence_minutes < _SUB_HOURLY_MINUTES

    if retention is None:
        if sub_hourly:
            raise DescriptorError(
                f"{unit_id}: trigger.cadence_minutes={cadence_minutes} is sub-hourly — its "
                "run_manifest_prefix takes one manifest per tick, not one per day — so it "
                "must declare `run_manifest_retention` (`<int> days`) and "
                "`run_manifest_retention_reason`. A missing declaration leaves the bucket's "
                "default to decide a cost nobody chose (precedent: D37)."
            )
        return

    if not _RETENTION_PATTERN.match(str(retention).strip()):
        raise DescriptorError(
            f"{unit_id}: run_manifest_retention {retention!r} is not `<positive integer> "
            "days` — the only shape this field is declared to accept."
        )
    if not str(reason or "").strip():
        raise DescriptorError(
            f"{unit_id}: run_manifest_retention is declared with no "
            "run_manifest_retention_reason. A retention number with no rationale is a knob "
            "nobody can safely change later."
        )


def _validate(unit_id: str, document: dict[str, Any], path: pathlib.Path) -> None:
    missing = [key for key in _REQUIRED_TOP_LEVEL if key not in document]
    if missing:
        raise DescriptorError(f"{path.name}: missing required field(s) {missing}")

    if document["unit_id"] != unit_id:
        raise DescriptorError(
            f"{path.name}: declares unit_id {document['unit_id']!r} but its filename says "
            f"{unit_id!r}. The filename is how a human finds the unit and the field is how "
            "the generator names it; a mismatch means one of the two is a lie."
        )

    cells = (document.get("audit") or {}).get("cells")
    if not isinstance(cells, dict):
        raise DescriptorError(f"{path.name}: audit.cells is missing or is not a mapping")
    if set(cells) != set(AUDIT_COLUMNS):
        raise DescriptorError(
            f"{path.name}: audit.cells declares {sorted(cells)}, but the audit's §3 register "
            f"scores exactly {list(AUDIT_COLUMNS)}. A unit with a missing column is a unit "
            "whose board row is complete over a question nobody asked."
        )
    for column, state in cells.items():
        if state not in AUDIT_CELL_STATES:
            raise DescriptorError(
                f"{path.name}: audit.cells.{column} is {state!r}, which is not one of the "
                f"audit's four cell states {sorted(AUDIT_CELL_STATES)}."
            )

    if set(document["clause_phase"]) != set(AUDIT_COLUMNS):
        raise DescriptorError(
            f"{path.name}: clause_phase must name every scored column; a column with no "
            "phase is a clause that can never hold a gate."
        )

    guards = document["guards"]
    if not isinstance(guards, dict):
        raise DescriptorError(f"{path.name}: guards is not a mapping")
    missing_guards = [g for g in GUARD_CLASSES if g not in guards]
    if missing_guards:
        raise DescriptorError(
            f"{path.name}: guards is missing {missing_guards}. Every unit answers every "
            "audit §4.1 class — with a state, or with an explicit N/A and its code. "
            "Silence on a degradation class is the degradation going unnamed."
        )
    unknown = [g for g in guards if g not in GUARD_CLASSES + OPTIONAL_GUARD_CLASSES]
    if unknown:
        raise DescriptorError(f"{path.name}: guards declares unknown class(es) {unknown}")
    for name, block in guards.items():
        if not isinstance(block, dict) or "state" not in block:
            raise DescriptorError(f"{path.name}: guards.{name} has no `state`")
        if block["state"] == "not_applicable":
            _check_na(f"guards.{name}", block, unit_id)
        if not str(block.get("note") or "").strip():
            raise DescriptorError(
                f"{path.name}: guards.{name} has no note. A guard state with no evidence "
                "behind it is a claim, and the board renders claims as findings."
            )

    freshness = document["freshness"] or {}
    if freshness.get("status") == "not_applicable":
        _check_na("freshness", freshness, unit_id)
    completeness = document["completeness"] or {}
    if completeness.get("status") == "not_applicable":
        _check_na("completeness", completeness, unit_id)

    if document["lifecycle"] == "retired":
        # `alpha-engine-config-I10823` deliverable 6. A retired unit's clauses
        # stop grading and render RETIRED with this block's reason — so a
        # retirement with no ruling or no reason would silently remove a unit
        # from every denominator on nobody's say-so. A retirement without a
        # reason is not a fact.
        retirement = document.get("retirement")
        missing_fields = [
            name
            for name in ("ruling", "reason")
            if not isinstance(retirement, dict) or not str(retirement.get(name) or "").strip()
        ]
        if missing_fields:
            raise DescriptorError(
                f"{path.name}: lifecycle is 'retired' but the `retirement:` block is missing or has "
                f"no {missing_fields}. Retiring a unit removes it from every gate's denominator; "
                "that needs the ruling that retired it and the reason, or it is a unit that "
                "disappeared (observability-policy §8.3: RETIRED is declared, never inferred)."
            )

    if not document["consumers"] and not str(document.get("consumers_reason") or "").strip():
        raise DescriptorError(
            f"{path.name}: declares no consumers and gives no reason. Plan §3's rule: a key "
            "with no surviving consumer gets a retirement decision, or a declared "
            "`consumers: []` WITH a reason, which renders as a finding. An empty list with "
            "no reason renders as nothing at all."
        )

    if "consumers_ruling" in document:
        # alpha-engine-config-I10873: the I10870 block rendered a kept,
        # unread unit MET — green over "nothing reads this". Renamed so a
        # stale copy fails loud instead of silently meaning nothing.
        raise DescriptorError(
            f"{path.name}: `consumers_ruling` was replaced by `consumers_decision` "
            f"(fields {list(_CONSUMERS_DECISION_FIELDS)}); a kept unit with no consumer renders "
            "UNCONNECTED, never MET (Brian ruling 2026-09-15, alpha-engine-config-I10873)."
        )

    classes = consumer_repo_classes()
    unclassified = sorted(
        {consumer_repo(c) for c in document["consumers"] or []} - classes["surviving"] - classes["retiring"]
    )
    if unclassified:
        raise DescriptorError(
            f"{path.name}: consumer repo(s) {unclassified} are in neither list of "
            f"{CONSUMER_REPOS_PATH.relative_to(REPO_ROOT)}. An unclassified repo would decide "
            "whether this unit is connected by default; classify it there."
        )

    decision = document.get("consumers_decision")
    if decision is not None:
        missing_decision_fields = [
            name
            for name in _CONSUMERS_DECISION_FIELDS
            if not isinstance(decision, dict) or not str(decision.get(name) or "").strip()
        ]
        if missing_decision_fields:
            raise DescriptorError(
                f"{path.name}: consumers_decision is missing {missing_decision_fields}. An "
                "UNCONNECTED clause is declared, never inferred (observability-policy §8.3 "
                "DISABLED: reason, owner and re-exam trigger), so every field is required."
            )
        if decision["decision"] not in CONSUMERS_DECISIONS:
            raise DescriptorError(
                f"{path.name}: consumers_decision.decision {decision['decision']!r} is not one of "
                f"{sorted(CONSUMERS_DECISIONS)}. Retiring a unit is `lifecycle: retired`."
            )
        if not _ISO_DATE.match(str(decision["ruled_on"]).strip()):
            raise DescriptorError(f"{path.name}: consumers_decision.ruled_on must be YYYY-MM-DD")
        surviving = [c for c in document["consumers"] or [] if consumer_repo(c) in classes["surviving"]]
        if surviving:
            raise DescriptorError(
                f"{path.name}: declares consumers_decision (kept with no consumer) but also a "
                f"surviving consumer {surviving}. A reincorporated unit is CONNECTED — delete the "
                "decision block in the same change that adds the consumer."
            )

    _check_retention(unit_id, document, path)


def load_units(directory: pathlib.Path | None = None) -> list[Unit]:
    """Every unit descriptor, validated, ordered by unit id.

    Raises on an empty directory: a clause generator that finds no units would
    publish a gate over an empty set and call it met.
    """
    root = directory or UNITS_DIR
    paths = sorted(root.glob("*.yaml"))
    if not paths:
        raise DescriptorError(
            f"no unit descriptors under {root}. A clause generator over an empty unit set "
            "would publish a gate that grades nothing and reads as a pass."
        )
    units: list[Unit] = []
    seen: set[str] = set()
    for path in paths:
        document = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(document, dict):
            raise DescriptorError(f"{path.name}: not a YAML mapping")
        unit_id = path.name.split("-", 1)[0]
        _validate(unit_id, document, path)
        if unit_id in seen:
            raise DescriptorError(f"duplicate unit id {unit_id!r} under {root}")
        seen.add(unit_id)
        units.append(Unit(unit_id=unit_id, path=path, raw=document))
    return units
